### ISSUE TITLE
Robotic Processing Unit (RPU) meta-ticket

### ISSUE THREAD

**Issue by vmayoral** [ros-acceleration/community#25]
*This ticket tracks the progress of the **Robotic Processing Unit (`RPU`)** [subproject](https://github.com/ros-acceleration/community) of the ROS 2 Hardware Acceleration Working Group. <ins>Content will be updated over time</ins>. In time, a repository will branch out of this effort containing additional resources. Expectation however should be for the discussion to remain in here for organizational purposes. You can send feedback about this subproject via [this form](https://docs.google.com/forms/d/e/1FAIpQLScHWIibgjdmyMd9ZrWitFVsQA8lKU8FQrih6h4Xa3uS_l523w/viewform).* 

#### The Robotic Processing Unit (`RPU`)
<ins>Definition</ins>: A robot-specific processing unit that maps ROS and robot computational graphs efficiently to underlying compute resources including CPUs, FPGAs and GPUs to obtain best performance.

#### Vision
The vision is that `RPU`s will empower robots with the ability to react faster (lower latency, higher throughput), consume less power, and deliver additional real-time capabilities with their custom compute architectures that fit best the usual robotics pipelines. This includes tasks across *sensing, perception, mapping, localization, motion control, low-level control and actuation*. 

#### Antigoal
The initial objective of this subproject is **not** to design a new physical device. Instead, existing off-the-shelf hardware acceleration development platforms will be used to prototype a robot-specific processing unit that performs best when it comes to ROS 2 and robot computational graphs. 

#### Sponsorship
The project is open to sponsorships and collaborations. For sponsoring the Robotic Processing Unit (`RPU`) contact [here](mailto:victor@accelerationrobotics.com).

#### Milestones

**Milestone 1: first demonstrators** - *raise awareness*
- [x] [Robotic Processing Unit (`RPU`) project announcement](https://news.accelerationrobotics.com/hardware-accelerated-ros2-pipelines/#new-subproject-robotic-processing-unit-rpu)
- [x] RFC to receive feedback and interest https://forms.gle/d4rCCoLpx9ciPiau9
- [x] Use cases driving the architecture and the development
  - [x] Perception (`image_pipeline` and friends)
    - [x] [`perception_2nodes`](https://github.com/ros-acceleration/acceleration_examples/tree/main/graphs/perception/perception_2nodes)
    - [x] [`perception_3nodes`](https://github.com/ros-acceleration/acceleration_examples/tree/main/graphs/perception/perception_3nodes)
    - [ ] *Maybe consider a more elaborated graph with multi-processing paths involving  more complex CV crunching, e.g. HOG (Histogram of Oriented Gradients)*?
  - [ ] ~~Navigation~~
    - [ ] ~~Still in dicussions, open to feedback.~~
- [x] Partition work into demonstrators, prioritize and execute
- [x] Disclose an initial hardware reference design of the Robotic Processing Unit https://github.com/ros-acceleration/robotic_processing_unit
- [ ] Disclose benchmarking results and discuss (connected to https://github.com/ros-acceleration/community/issues/10)
